[package]
name = "float_extras"
version = "0.1.0"
authors = ["yjh0502 <yjh0502@gmail.com>"]

description = "extra floating-point mach functions from c math library"
repository = "https://github.com/yjh0502/float_extras"

license = "Apache-2.0"

[dependencies]
libc = "0.2.22"
